# Base image
FROM ubuntu:22.04

# Setup ambiente non interattivo per evitare prompt durante le installazioni
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Rome

# Aggiornamento di sistema
RUN apt-get update -y && apt-get upgrade -y

# installazione Apache e PHP
RUN apt-get install -y php apache2 python3-pip

# Copia dei file di configurazione di Apache

# COPY ./apache-config/000-default.conf /etc/apache2/sites-available/000-default.conf
# COPY ./apache-config/ports.conf /etc/apache2/ports.conf

# Esposizione porte 80 e 8080
EXPOSE 80
#EXPOSE 8080

# Esecuzione di Apache in foreground
CMD ["apachectl", "-D", "FOREGROUND"]